# Project 1

In [ ]:
# Install dependencies.
!pip install -q "numpy>=2,<3" tensorflow

## Load and inspect the training data

Load the paired pickle files from `data/` and inspect the first five samples. Each label corresponds to the sample at the same list index.


In [ ]:
import pickle
import numpy as np

# Run this notebook from the project1/ directory.
with open("data/CSCE-636-Project-1-Train-n_k_m_P", "rb") as file:
    features = pickle.load(file)

with open("data/CSCE-636-Project-1-Train-mHeights", "rb") as file:
    labels = pickle.load(file)

if len(features) != len(labels):
    raise ValueError(
        f"Sample/label count mismatch: {len(features)} samples, {len(labels)} labels."
    )

first_five_features = features[:5]
first_five_labels = labels[:5]
print(f"Loaded {len(features):,} samples and {len(labels):,} corresponding labels.")

# Print the first five samples and their corresponding labels.
for index, ((n, k, m, P), m_height) in enumerate(
    zip(first_five_features, first_five_labels)
):
    if n != 9 or k not in (4, 5, 6) or not (2 <= m <= n - k):
        raise ValueError(f"Sample at index {index} has invalid n, k, or m.")
    if not isinstance(P, np.ndarray) or P.shape != (k, n - k):
        raise ValueError(f"Sample at index {index}: expected a NumPy array of shape {(k, n - k)}.")

    print("=" * 64)
    print(f"Sample {index + 1} (list index {index})")
    print(f"n = {n}, k = {k}, m = {m}")
    print(f"P.shape = {P.shape}; expected (k, n-k) = {(k, n - k)}")
    print(f"P dtype: {P.dtype}")
    print("P contents:")
    with np.printoptions(threshold=np.inf, floatmode="unique", linewidth=120):
        print(P)
    print(f"True m-height = {m_height!r}")



Loaded 3,833,203 samples and 3,833,203 corresponding labels.
Sample 1 (list index 0)
n = 9, k = 4, m = 4
P.shape = (4, 5); expected (k, n-k) = (4, 5)
P dtype: float64
P contents:
[[  7.  29.  32.  33. -42.]
 [ 24.  38.  -3.  26.  17.]
 [ 28. -35. -20.  32. -29.]
 [-32. -14.   1. -47. -18.]]
True m-height = 415.96346010439976
Sample 2 (list index 1)
n = 9, k = 4, m = 3
P.shape = (4, 5); expected (k, n-k) = (4, 5)
P dtype: float64
P contents:
[[  99.   29.  -98.   81.  -22.]
 [  24.   -3.  -48.   52. -100.]
 [ -34.   38.  -70.   55.   21.]
 [ -78.  -37.   59.  -41.  -32.]]
True m-height = 176.92456578763563
Sample 3 (list index 2)
n = 9, k = 4, m = 2
P.shape = (4, 5); expected (k, n-k) = (4, 5)
P dtype: float64
P contents:
[[-41.   6.  31. -45.  48.]
 [ 10. -19. -39.  40.   1.]
 [-22. -23.   3.  -8.  38.]
 [ 24.  18. -26.  22.  -8.]]
True m-height = 34.156780049509464
Sample 4 (list index 3)
n = 9, k = 4, m = 3
P.shape = (4, 5); expected (k, n-k) = (4, 5)
P dtype: float64
P contents:
[[ 